### ISSUE TITLE
NoSuchMethodException ItemRegistry.add(Ljava/lang/Object;)

### ISSUE THREAD

**Issue by dragondagda** [eclipse/smarthome#4504]
After upgrading from 0.9.0.b5 to b6 we're facing an issue with the ItemRegistry. When calling either .add(Item) or .get(String) we are getting a NochSuchMethodException:

`2017-11-06 11:08:41.421 ERROR org.eclipse.smarthome.core.internal.events.OSGiEventManager - Dispatching/filtering event for subscriber 'org.eclipse.smarthome.core.events.EventSubscriber' failed: java.lang.NoSuchMethodError: org.eclipse.smarthome.core.items.ItemRegistry.add(Ljava/lang/Object;)Ljava/lang/Object;
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.eclipse.smarthome.core.items.ItemRegistry.add(Ljava/lang/Object;)Ljava/lang/Object;
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:206)
at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:194)
at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:83)
at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:67)
at org.eclipse.smarthome.core.internal.events.OSGiEventManager.dispatchESHEvent(OSGiEventManager.java:203)
at org.eclipse.smarthome.core.internal.events.OSGiEventManager.handleEvent(OSGiEventManager.java:176)
at org.eclipse.smarthome.core.internal.events.OSGiEventManager.handleEvent(OSGiEventManager.java:158)
at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415)
at org.apache.felix.eventadmin.impl.tasks.HandlerTask.runWithoutBlacklistTiming(HandlerTask.java:102)
at org.apache.felix.eventadmin.impl.tasks.SyncDeliverTasks.execute(SyncDeliverTasks.java:104)
at org.apache.felix.eventadmin.impl.tasks.AsyncDeliverTasks$TaskExecuter.run(AsyncDeliverTasks.java:166)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.eclipse.smarthome.core.items.ItemRegistry.add(Ljava/lang/Object;)Ljava/lang/Object;
[..]`

This is how we call the methods:

- itemRegistry.add(new StringItem("itemxyz"))
- itemRegistry.get("itemxyz") - We changed this to 'itemRegistry.getItem("itemxyz")', afterwards it worked

We are not sure if this is an issue with the introduced Identifiable Interface or our configuration. 

Hopefully you can help us with this

**Comment by dragondagda** [comment]
Never mind. We found the problem. We are building our project with tycho and used a channel of our private p2 repository which was pointing to beta5 instead of beta6. This was used when creating our own bundles and the beta6 bundles were added via feature.xml by karaf.
